# Grants access to the shared gitlab runners
default:
  tags:
    - shared

variables:
  GITHUB_TOKEN: $GITHUB_TOKEN
  GITLAB_SYNC_TOKEN: $GITLAB_SYNC_TOKEN
  RH_CA_FILENAME: RH-IT-Root-CA.crt

# Save job output to a variable
.sync-default: &sync-default
  image:
    name: quay.io/emingora/gitlab-github-sync:latest
  before_script:
    - "[[ ! -f ${RH_CA_FILENAME} ]] && curl -k -s 'https://certs.corp.redhat.com/certs/{2015,2022}-IT-Root-CA.pem' > ${RH_CA_FILENAME}"
    - ls ${PWD}/${RH_CA_FILENAME}
    - export NODE_EXTRA_CA_CERTS=${PWD}/${RH_CA_FILENAME}
    - export GIT_SSL_CAINFO=${PWD}/${RH_CA_FILENAME}
    - git config --global http.sslCAInfo ${PWD}/${RH_CA_FILENAME}

stages:
  - sync

📦 Sync master branch:
  <<: *sync-default
  stage: sync
  rules:
    - if: $JOB_ID == "sync"
  script:
    - git clone -b master https://$GITHUB_TOKEN@github.com/RedHatInsights/uhc-portal uhc-portal
    - cd uhc-portal
    - git remote add gitlab https://GITLAB_SYNC_TOKEN:$GITLAB_SYNC_TOKEN@gitlab.cee.redhat.com/service/uhc-portal
    - git push gitlab master --force

📦 Sync stable branch:
  <<: *sync-default
  stage: sync
  rules:
    - if: $JOB_ID == "sync"
  script:
    - git clone -b stable https://$GITHUB_TOKEN@github.com/RedHatInsights/uhc-portal uhc-portal
    - cd uhc-portal
    - git remote add gitlab https://GITLAB_SYNC_TOKEN:$GITLAB_SYNC_TOKEN@gitlab.cee.redhat.com/service/uhc-portal
    - git push gitlab stable --force
