codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.stories.tsx"
  - "**/fixtures/**"
  - "**/mocks/**"
  - "**/__mocks__/**"
  - "**/types/**"
  - "**/constants/**"
  - "**/index.ts"
  - "**/index.tsx"
