apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/uhc-portal?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/platform-ui/docker-build-run-unit-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ocm-ui
    appstudio.openshift.io/component: uhc-portal
    pipelines.appstudio.openshift.io/type: build
  name: uhc-portal-on-pull-request
  namespace: ocm-ui-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocm-ui-tenant/uhc-portal:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex

      npm install -g yarn

      yarn install

      # todo - use NODE_OPTIONS="--max-old-space-size=..."
      # todo - reduce unit-tests-memory-* back to 8Gi and see if it's okay still

      # todo - move to npm script
      node --max-old-space-size=1536 ./node_modules/.bin/eslint src 'run/*js' --ext mjs,js,jsx,ts,tsx

      yarn prettier

      # yarn test --runInBand --no-cache --coverage=false
      TZ=America/New_York LC_ALL=en_US.utf8 node --max-old-space-size=4096 --no-compilation-cache --expose-gc ./node_modules/.bin/jest --logHeapUsage --runInBand --no-cache --coverage=false
  - name: unit-tests-memory-request
    value: "8Gi"
  - name: unit-tests-memory-limit
    value: "8Gi"
  - name: unit-tests-cpu-request
    value: "4000m"
  - name: unit-tests-cpu-limit
    value: "4000m"
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-uhc-portal
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
