apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/uhc-portal?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/platform-ui/docker-build-run-unit-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ocm-ui
    appstudio.openshift.io/component: uhc-portal
    pipelines.appstudio.openshift.io/type: build
  name: uhc-portal-on-pull-request
  namespace: ocm-ui-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocm-ui-tenant/uhc-portal:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex

      npm install -g yarn

      yarn install
      NODE_OPTIONS='--max-old-space-size=1536' yarn lint
      yarn prettier
      NODE_OPTIONS='--max-old-space-size=4096' yarn test-no-coverage --runInBand --no-cache
  - name: unit-tests-memory-request
    value: "64Gi"
  - name: unit-tests-memory-limit
    value: "64Gi"
  - name: unit-tests-cpu-request
    value: "12000m"
  - name: unit-tests-cpu-limit
    value: "12000m"
  pipelineRef:
    name: docker-build
  taskRunTemplate:
    serviceAccountName: build-pipeline-uhc-portal
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
