apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/uhc-portal?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/platform-ui/docker-build-run-all-tests-v2.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ocm-ui
    appstudio.openshift.io/component: uhc-portal
    pipelines.appstudio.openshift.io/type: build
  name: uhc-portal-on-pull-request
  namespace: ocm-ui-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocm-ui-tenant/ocm-ui/uhc-portal:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: e2e-app-port
    value: "8000"
  - name: unit-tests-script
    value: |
      #!/bin/bash
      echo "wat"
  - name: run-app-script
    value: |
      #!/bin/sh
      set -e
      echo "Starting application with Caddy using ConfigMap Caddyfile..."
      exec caddy run --config /etc/caddy/Caddyfile
  - name: e2e-tests-script
    value: |
      #!/bin/bash
      echo "wat"
  - name: e2e-credentials-secret
    value: ocm-ui-credentials-secret
  - name: frontend-proxy-routes-configmap
    value: ocm-ui-dev-proxy-caddyfile
  - name: e2e-hcc-env
    value: prod
  - name: e2e-hcc-env-url
    value: https://console.dev.redhat.com
  pipelineRef:
    name: docker-build-v2
  taskRunTemplate:
    serviceAccountName: build-pipeline-uhc-portal
  taskRunSpecs:
    # extend the unit-tests pipeline task to increase RAM
    - pipelineTaskName: run-unit-tests
      stepSpecs:
        - name: unit-tests
          computeResources:
            requests:
              memory: "6Gi"
            limits:
              memory: "6Gi"
    - pipelineTaskName: run-e2e-tests
      stepSpecs:
        - name: e2e-tests
          computeResources:
            requests:
              memory: "10Gi"
            limits:
              memory: "10Gi"
      podTemplate:
        hostAliases:
          - ip: "::1"
            hostnames:
              - "prod.foo.redhat.com"
          - ip: "127.0.0.1"
            hostnames:
              - "prod.foo.redhat.com"
        volumes:
          - name: test-app-caddyfile
            configMap:
              name: ocm-ui-app-caddy-config
      sidecarSpecs:
        - name: run-application
          volumeMounts:
            - name: test-app-caddyfile
              mountPath: /etc/caddy
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
