apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/RedHatInsights/uhc-portal?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://raw.githubusercontent.com/RedHatInsights/konflux-pipelines/refs/heads/main/pipelines/platform-ui/docker-build-run-all-tests.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ocm-ui
    appstudio.openshift.io/component: uhc-portal
    pipelines.appstudio.openshift.io/type: build
  name: uhc-portal-on-pull-request
  namespace: ocm-ui-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocm-ui-tenant/ocm-ui/uhc-portal:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: build-tools/Dockerfile
  - name: test-app-name
    value: uhc-portal
  - name: test-app-port
    value: "8000"
  - name: unit-tests-script
    value: |
      #!/bin/bash
      set -ex
      npm install -g yarn
      yarn install
      # cap the linter's heap size, as it tends to hog the RAM,
      # causing the OS to kill the process due to out-of-memory errors
      NODE_OPTIONS='--max-old-space-size=4096' yarn lint
      yarn prettier
      yarn test --run-in-band --no-cache
  - name: run-app-script
    value: |
      #!/bin/sh
      set -e
      echo "Starting application with Caddy using ConfigMap Caddyfile..."
      exec caddy run --config /etc/caddy/Caddyfile
  - name: e2e-tests-script
    value: |
      #!/bin/bash
      set -ex

      # Wait for dev server to be ready
      timeout 120s bash -c 'until curl -k https://stage.foo.redhat.com:1337 > /dev/null 2>&1; do
        echo "Waiting for dev server to be ready"
        sleep 5
      done'
      echo "Dev server ready!"

      # Map Konflux secret keys to what Playwright expects
      export TEST_WITHQUOTA_USER="$E2E_USER"
      export TEST_WITHQUOTA_PASSWORD="$E2E_PASSWORD"

      # Install Playwright browsers
      echo "Installing Playwright browsers..."
      npx playwright install --with-deps chromium

      # Run CI-tagged tests
      echo "Running Playwright tests..."
      npx playwright test --grep @ci
  - name: e2e-credentials-secret
    value: ocm-ui-credentials-secret
  - name: frontend-proxy-routes-configmap
    value: ocm-ui-dev-proxy-caddyfile
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/RedHatInsights/konflux-pipelines
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/platform-ui/docker-build-run-all-tests.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-uhc-portal
  taskRunSpecs:
    - pipelineTaskName: run-unit-tests
      stepSpecs:
        - name: unit-tests
          computeResources:
            requests:
              memory: "6Gi"
            limits:
              memory: "6Gi"
    - pipelineTaskName: run-e2e-tests
      serviceAccountName: build-pipeline-uhc-portal
      podTemplate:
        hostAliases:
          - ip: "::1"
            hostnames:
              - "stage.foo.redhat.com"
          - ip: "127.0.0.1"
            hostnames:
              - "stage.foo.redhat.com"
        volumes:
          - name: test-app-caddyfile
            configMap:
              name: ocm-ui-app-caddy-config
      sidecarSpecs:
        - name: run-application
          volumeMounts:
            - name: test-app-caddyfile
              mountPath: /etc/caddy
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
