name:  E2e CI Playwright

on:
  push:
    branches:
      - 'playwright-migration'
  pull_request:
    branches:
      - 'playwright-migration'
jobs:
  install:
    name: Playwright E2E - ${{ matrix.os }} - Install - Node ${{ matrix.node-version }}
    concurrency:
      group: playwright-e2e-install-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.merge_commit_sha }}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        with:
          path: './node_modules'
          key: playwright-e2e-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Check uncommitted changes
        if: ${{ always() }}
        # Check that Git working tree is clean after running `install` command.
        # The `git` command exits with 1 and fails the build if there are any uncommitted changes.
        run: git diff HEAD --exit-code

  playwright-e2e-test:
    name: Playwright E2E - ${{ matrix.os }} - e2e Tests - Node ${{ matrix.node-version }}
    concurrency:
      group: playwright-e2e-test-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    needs: [install]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: '${{ github.event.pull_request.merge_commit_sha }}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v4
        with:
          path: './node_modules'
          key: playwright-e2e-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Add hosts
        run: make dev-env-setup
      - name: Check hosts
        run: cat /etc/hosts
      - name: Create playwright.env.json from secret
        run: |
          echo "Creating playwright.env.json..."
          echo '${{ secrets.PLAYWRIGHT_ENV_JSON }}' > playwright.env.json

          # Add unique identifiers to avoid resource conflicts
          BUILD_ID="${{ github.run_id }}"

          # Install jq if not available
          if ! command -v jq &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

          # Add build identifier to avoid conflicts
          jq ". + {\"BUILD_IDENTIFIER\": \"${BUILD_ID}\"}" playwright.env.json > tmp.json && mv tmp.json playwright.env.json

          # Validate JSON using jq
          if jq empty playwright.env.json > /dev/null 2>&1; then
            echo "playwright.env.json is valid JSON"
          else
            echo "ERROR: playwright.env.json is not valid JSON!"
            exit 1
          fi
      - name: Execute tests
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
          BROWSER: chromium
          BASE_URL: https://prod.foo.redhat.com:1337/openshift/
        run: |
          yarn start:ci --env logging=quiet --no-client-overlay &
          NODE_TLS_REJECT_UNAUTHORIZED=0 yarn wait-on -i 5000 https://prod.foo.redhat.com:1337/openshift/
          NODE_TLS_REJECT_UNAUTHORIZED=0 yarn playwright-e2e-ci
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: playwright-e2e-facts
          retention-days: 5
          path: |
            playwright-artifacts/
